export const SET_EMAIL = 'SET_EMAIL'

export const SET_TOKEN = 'SET_TOKEN'

export const SET_UID = 'SET_UID'

export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY'

export const SET_ASSOCIATE_RESTAURANT = 'SET_ASSOCIATE_RESTAURANT'

export const SET_RESTAURANTS = 'SET_RESTAURANTS'

export const SET_REVIEWS = 'SET_REVIEWS'

export const SET_FOODS = 'SET_FOODS'

export const SET_BANNERS = 'SET_BANNERS'

export const SET_DISCOVER = 'SET_DISCOVER'
